//RANDOM PATRON TABLE
var PatronTable={
 "11":"assassin", 	//Criminal Patrons
 "12":"smuggler",
 "13":"terrorist",
 "14":"embezzler",
 "15":"thief",
 "16":"revolutionary",
 "21":"clerk",		//Local Leaders
 "22":"administrator",
 "23":"mayor",
 "24":"minor noble",
 "25":"physician",
 "26":"tribal leader",
 "31":"diplomat",	//High Society Patrons
 "32":"courier",
 "33":"spy",
 "34":"ambassador",
 "35":"noble",
 "36":"police officer",
 "41":"merchant",	//Commercial Patrons
 "42":"free trader",
 "43":"broker",
 "44":"corporate executive",
 "45":"corporate agent",
 "46":"financier",
 "51":"belter",		//Spacer Patrons
 "52":"researcher",
 "53":"naval officer",
 "54":"pilot",
 "55":"starport administrator",
 "56":"scout",
 "61":"alien",		//Unusual Patrons
 "62":"playboy",
 "63":"stowaway",
 "64":"family relative",
 "65":"agent of a foreign power",
 "66":"imperial agent"
 };

var MISSIONTARGETTYPES={};
	MISSIONTARGETTYPES.goods=1;
	MISSIONTARGETTYPES.object=2;
	MISSIONTARGETTYPES.place=3;
	MISSIONTARGETTYPES.person=4;
	MISSIONTARGETTYPES.org=5;
	MISSIONTARGETTYPES.ship=6;
	MISSIONTARGETTYPES.special=-1;
	MISSIONTARGETTYPES.starsystem=-2
	
	

//RANDOM PATRON MISSION TABLE
var PatronMissionTable={
 "11":{"mission":"assasinate a target", "targettypes":[4]},
 "12":{"mission":"frame a target", "targettypes":[4,5]},
 "13":{"mission":"destroy a target", "targettypes":[1,2,3,5,6]},
 "14":{"mission":"steal from a target", "targettypes":[3,4,5,6]},
 "15":{"mission":"aid in a burglary", "targettypes":[1,2,3,4,5,6]},
 "16":{"mission":"stop a burglary", "targettypes":[1,2,3,4,5,6]},
 "21":{"mission":"retrieve data or an object from a secure facility", "targettypes":[3,6]},
 "22":{"mission":"discredit a target", "targettypes":[4,5]},
 "23":{"mission":"find a lost cargo", "targettypes":[1,2]},
 "24":{"mission":"find a lost person", "targettypes":[4]},
 "25":{"mission":"deceive a target", "targettypes":[4,5]},
 "26":{"mission":"sabotage a target", "targettypes":[2,3,5,6]},
 "31":{"mission":"transport goods", "targettypes":[1,2]},
 "32":{"mission":"transport a person", "targettypes":[4]},
 "33":{"mission":"transport data", "targettypes":[1,2,3,4,5,6]},
 "34":{"mission":"transport goods secretly", "targettypes":[1,2]},
 "35":{"mission":"transport goods quickly", "targettypes":[1,2]},
 "36":{"mission":"transport dangerous goods", "targettypes":[1,2]},
 "41":{"mission":"investigate a crime", "targettypes":[1,2,3,4,5,6]},
 "42":{"mission":"investigate a theft", "targettypes":[1,2,3,4,5,6]},
 "43":{"mission":"investigate a murder", "targettypes":[4]},
 "44":{"mission":"investigate a mystery", "targettypes":[1,2,3,4,5,6]},
 "45":{"mission":"investigate a target", "targettypes":[1,2,3,4,5,6]},
 "46":{"mission":"investigate an event", "targettypes":[1,2,3,4,5,6]},
 "51":{"mission":"join an expedition", "targettypes":[1,2,3,6]},
 "52":{"mission":"survey a planet", "targettypes":[-2]}, // What do to with these?
 "53":{"mission":"explore a new system", "targettypes":[-2]}, //
 "54":{"mission":"explore a ruin", "targettypes":[-1]},//
 "55":{"mission":"salvage a ship", "targettypes":[6, -2]},
 "56":{"mission":"capture a creature", "targettypes":[-1]}, //
 "61":{"mission":"hijack a ship", "targettypes":[6]},
 "62":{"mission":"entertain a noble", "targettypes":[4]},
 "63":{"mission":"protect a target", "targettypes":[1,2,3,4,5,6]},
 "64":{"mission":"save a target", "targettypes":[1,2,3,4,5,6]},
 "65":{"mission":"aid a target", "targettypes":[3,4,5,6]},
 "66":{"mission":"It's a trap! (The patron intends to betray the characters.)","targettypes":[-1]}//
 };

//RANDOM MISSION TARGETS TABLE
var PatronMissionTargetTable={
 "11":"common trade goods",			//Trade Goods
 "12":"common trade goods",
 "13":"random trade goods",
 "14":"random trade goods",
 "15":"illegal trade goods",
 "16":"illegal trade goods",
 "21":"computer data",				//Objects
 "22":"personal effects",
 "23":"works of art",
 "24":"works of art",
 "25":"historical artefact",
 "26":"weapon",
 "31":"starport",					//Places
 "32":"asteroid base",
 "33":"city",
 "34":"research station",
 "35":"bar or nightclub",
 "36":"medical facility",
 "41":"[roll on the patron table]",	//NPCs
 "42":"[roll on the patron table]",
 "43":"[roll on the patron table]",
 "44":"[roll on the random opposition table]",
 "45":"[roll on the random opposition table]",
 "46":"[roll on the random opposition table]",
 "51":"local government",			//Organizations
 "52":"planetary government",
 "53":"corporation",
 "54":"imperial intelligence",
 "55":"criminal syndicate",
 "56":"criminal gang",
 "61":"free trader",				//Vessels
 "62":"yacht",
 "63":"cargo hauler",
 "64":"police cutter",
 "65":"space station",
 "66":"warship"
 };

//RANDOM OPPOSITION TABLE
var PatronMissionOppositionTable=
 {"11":"animals",							//Low Tech
 "12":"large animals",
 "13":"bandits and thieves",
 "14":"fearful peasants",
 "15":"local authorities",
 "16":"local lord",
 "21":"criminals (thugs or corsairs)",		//Average Tech
 "22":"criminals (thieves or saboteurs)",
 "23":"police (ordinary security forces)",
 "24":"police (inspectors and detectives",
 "25":"corporate (agents)",
 "26":"corporate (legal)",
 "31":"starport security",					//High Tech
 "32":"imperial marines",
 "33":"interstellar corporation",
 "34":"alien (private citizen or corporation)",
 "35":"alien (govnernment)",
 "36":"space travellers or rival ship",
 "41":"target is in deep space",			//Environmental
 "42":"target is in orbit",
 "43":"hostile weather conditions",
 "44":"dangerous organisms or radiation",
 "45":"target is in a dangerous region",
 "46":"target is in a restricted area",
 "51":"target is under electronic observation",	//Technology
 "52":"hostile guard robots or ships",
 "53":"biometric identification required",
 "54":"mechanical failure or computer hacking",
 "55":"characters are under surveillance",
 "56":"out of fuel or ammunition",
 "61":"police investigation",					//Social
 "62":"legal barriers",
 "63":"nobility",
 "64":"government officials",
 "65":"target is protected by a third party",
 "66":"hostages"
 };
 
//RANDOM STARPORT ENCOUNTERS TABLE
var StarportEncountersTable=
 {"11":"maintenance robot at work",
 "12":"trade ship arrives or departs",
 "13":"captain argues about fuel prices",
 "14":"news report about pirate activity on a starport screen draws a crowd",
 "15":"bored clerk makes life difficult for the characters",
 "16":"local merchant with cargo to transport seeks a ship",
 "21":"dissident tries to claim sanctuary from planetary authorities",
 "22":"traders from offworld argue with local brokers",
 "23":"technician repairing starport computer system",
 "24":"reporter asks for news from offworld",
 "25":"bizarre cultural performance",
 "26":"patron argues with another group of travellers",
 "31":"military vessel arrives or departs",
 "32":"demonstration outside starport",
 "33":"escaped prisoner(s) beg(s) for passage offworld",
 "34":"impromptu bazaar of bizarre items",
 "35":"security patrol",
 "36":"unusual alien",
 "41":"traders offer spare parts and supplies at cut-price rates",
 "42":"repar yard catches fire",
 "43":"passenger liner arrives or departs",
 "44":"servant robot offers to guide characters around the spaceport",
 "45":"trader from a distant system selling strange curios",
 "46":"old crippled belter asks for spare change and complains about drones taking his job",
 "51":"patron offers the characters a job",
 "52":"passenger looking for a ship",
 "53":"religious pilgrims try to convert the characters",
 "54":"cargo hauler arrives or departs",
 "55":"scout ship arrives or departs",
 "56":"illegal or dangerous goods are impounded",
 "61":"pickpocket tries to steal from the characters",
 "62":"drunken crew pick a fight",
 "63":"government officials investigate the characters",
 "64":"random security sweep scans characters & baggage",
 "65":"starport is temporarily shut down for security reasons",
 "66":"damaged ship makes emergency docking"
 };
 
 
//RURAL ENCOUNTERS TABLE
var RuralEncountersTable=
{"11":"wild animal",
 "12":"agricultural robots",
 "13":"crop sprayer drone flies overhead",
 "14":"damaged agricultural robot being repaired",
 "15":"small, isolationist community",
 "16":"noble hunting party",
 "21":"wild animal",
 "22":"local landing field",
 "23":"lost child",
 "24":"travelling merchant caravan",
 "25":"cargo convoy",
 "26":"police chase",
 "31":"wild animal",
 "32":"telecommunications black spot",
 "33":"security patrol",
 "34":"military facility",
 "35":"bar or waystation",
 "36":"grounded spacecraft",
 "41":"wild animal",
 "42":"small community (quiet place to live)",
 "43":"small community (on a trade route)",
 "44":"small community (festival in progress)",
 "45":"small community (in danger)",
 "46":"small community (not what it seems)",
 "51":"wild animal",
 "52":"unusual weather",
 "53":"difficult terrain",
 "54":"unusual creature",
 "55":"isolated homestead (welcoming)",
 "56":"isolated homestead (unfriendly)",
 "61":"wild animal",
 "62":"private villa",
 "63":"monastery or retreat",
 "64":"experimental farm",
 "65":"ruined structure",
 "66":"research facility"
 };

//URBAN ENCOUNTERS TABLE
var UrbanEncountersTable=
{"11":"street riot in progress",
 "12":"characters pass a charming restaurant",
 "13":"trader in illegal goods",
 "14":"public argument",
 "15":"sudden change of weather",
 "16":"NPC asks for the character's help",
 "21":"characters pass a bar or pub",
 "22":"characters pass a theatre or other entertainment venue",
 "23":"curiosity shop",
 "24":"street market stall tries to sell the characters something",
 "25":"fire, come breach or other emergency in progress",
 "26":"attempted robbery of characters",
 "31":"vehicle accident involving characters",
 "32":"low-flying spacecraft flies overhead",
 "33":"alien or other offworlder",
 "34":"random NPC bumps into character",
 "35":"pickpocket",
 "36":"media team or journalist",
 "41":"security patrol",
 "42":"ancient building or archive",
 "43":"festival",
 "44":"someone is following the characters",
 "45":"unusual cultural group or event",
 "46":"planetary official",
 "51":"characters spot someone they recognize",
 "52":"public demonstration",
 "53":"robot or other servant passes characters",
 "54":"prospective patron",
 "55":"crime such as robbery or attack in progress",
 "56":"street preacher rants at the characters",
 "61":"news broadcast on public screens",
 "62":"sudden curfew or other restriction on movement",
 "63":"unusually empty or quiet street",
 "64":"public announcement",
 "65":"sports event",
 "66":"imperial dignitary"
 };
 
 var encountersTables=[StarportEncountersTable,RuralEncountersTable,UrbanEncountersTable];

//RANDOM TRAITS TABLE
var NPCTraitsTable=
{"11":"loyal",
 "12":"distracted by other worries",
 "13":"in debt to criminals",
 "14":"makes very bad jokes",
 "15":"will betray characters",
 "16":"aggressive",
 "21":"has secret allies",
 "22":"secret anagathic user",
 "23":"looking for something",
 "24":"helpful",
 "25":"forgetful",
 "26":"wants to hire the characters",
 "31":"has useful contacts",
 "32":"artistic",
 "33":"easily confused",
 "34":"unusually ugly",
 "35":"worried about current situation",
 "36":"shows pictures of his children",
 "41":"rumor-monger",
 "42":"unusually provincial",
 "43":"drunkard or drug addict",
 "44":"government informant",
 "45":"mistakes a player character for someone else",
 "46":"possesses unusually advanced technology",
 "51":"unusually handsome or beautiful",
 "52":"spying on the characters",
 "53":"possesses TAS membership",
 "54":"is secretly hostile towards the characters",
 "55":"wants to borrow money",
 "56":"is convinced the characters are dangerous",
 "61":"involved in political intrigue",
 "62":"has a dangerous secret",
 "63":"wants to get offplanet as soon as possible",
 "64":"attracted to a player character",
 "65":"from offworld",
 "66":"possesses telepathy or other unusual quality"
 };

//CONTACTS, ALLIES, RIVALS AND ENEMIES TABLE
var NPCOccupationsTable=
{"11":"naval officer",
 "12":"imperial diplomat",
 "13":"crooked trader",
 "14":"medical doctor",
 "15":"eccentric scientist",
 "16":"mercenary",
 "21":"famous performer",
 "22":"alien thief",
 "23":"free trader",
 "24":"explorer",
 "25":"marine captain",
 "26":"corporate executive",
 "31":"researcher",
 "32":"cultural attache",
 "33":"religious leader",
 "34":"conspirator",
 "35":"rich noble",
 "36":"artificial intelligence",
 "41":"bored noble",
 "42":"planetary governor",
 "43":"inveterate gambler",
 "44":"crusading journalist",
 "45":"doomsday cultist",
 "46":"corporate agent",
 "51":"criminal syndicate",
 "52":"military governor",
 "53":"army quartermaster",
 "54":"private investigator",
 "55":"starport administrator",
 "56":"retired admiral",
 "61":"alien ambassador",
 "62":"smuggler",
 "63":"weapons inspector",
 "64":"elder statesman",
 "65":"planetary warlord",
 "66":"imperial agent"
 };

//SPACE ENCOUNTERS TABLE
var SpaceEncountersTable=
{"01":"alien derelict (possible salvage)",
"02":"*solar flare (1d6 100 rads)",
"03":"asteroid (empty rock)",
"04":"ore-bearing asteroid (possible mining)",
"05":"alien vessel (on a mission(",
"06":"rock hermit (inhabited rock)",
"11":"*pirate",
"12":"derelict vessel (possible salvage)",
"13":"space station (1-4: derelict)",
"14":"comet (may be ancient derelict at its core)",
"15":"ore-bearing asteroid (possible mining)",
"16":"ship in distress",
"21":"pirate",
"22":"free trader",
"23":"*micrometeorite storm (collision!)",
"24":"*hostile vessel (roll again for type)",
"25":"mining ship",
"26":"scout ship",
"31":"alien vessel (1-3: trader, 4-6: explorer, 6: spy)",
"32":"space junk (possible salvage)",
"33":"far trader",
"34":"derelict (possible salvage)",
"35":"safari or science vessel",
"36":"escape pod",
"41":"passenger liner",
"42":"ship in distress",
"43":"colony ship or passenger liner",
"44":"scout ship",
"45":"space station",
"46":"x-boat courier",
"51":"*hostile vessel (roll again for type)",
"52":"garbage ejected from a ship",
"53":"medical ship or hospital",
"54":"lab ship or scout",
"55":"*patron (roll on the patron table)",
"56":"police ship",
"61":"unusually daring pirate",
"62":"noble yacht",
"63":"warship",
"64":"cargo vessel",
"65":"navigational buoy or beacon",
"66":"unusual ship",
"71":"*collision with space junk (collision!)",
"72":"automated vessel",
"73":"free trader",
"74":"dumped cargo pod (roll on random trade goods table)",
"75":"police vessel",
"76":"cargo hauler",
"81":"passenger liner",
"82":"orbital factory (roll on random trade goods)",
"83":"orbital habitat",
"84":"orbital habitat",
"85":"communications satellite",
"86":"defense satellite",
"91":"pleasure craft",
"92":"space station",
"93":"police vessel",
"94":"cargo hauler",
"95":"system defense boat",
"96":"grand fleet warship"
};

//RANDOM PASSENGERS TABLE
var RandomPassengersTable=
{"11":"political refugee",
"12":"economic refugee",
"13":"starting a new life offworld",
"14":"mercenary",
"15":"spy",
"16":"corporate executive",
"21":"out to see the universe",
"22":"tourist (1-3 irritating, 4-6 charming)",
"23":"wide-eyed yokel",
"24":"adventurer",
"25":"explorer",
"26":"claustrophobic",
"31":"expectant mother",
"32":"wants to stowaway or join the crew",
"33":"possesses something dangerous or illegal",
"34":"causes trouble (1-3 drunkard, 4-5 violent, 6 insane)",
"35":"unusually pretty or handsome",
"36":"engineer (Mechanic & Engineer skills of 1d6-1 each)",
"41":"ex-scout",
"42":"wanderer",
"43":"thief or other criminal",
"44":"scientist",
"45":"journalist or researcher",
"46":"entertainer (Steward & Perform skills of 1d6-1 each)",
"51":"gambler (Gambling skill of 1d6-1)",
"52":"rich noble - complains a lot",
"53":"rich noble - eccentric",
"54":"rich noble - raconteur",
"55":"diplomat on a mission",
"56":"agent on a mission",
"61":"patron",
"62":"alien",
"63":"bounty hunter",
"64":"on the run",
"65":"wants to be on board the PC's ship for some reason",
"66":"hijacker or pirate agent"
};
