
{"11":{"type":"Basic Electronics",
		"available":"All",
		"maxTonsDie":"1d6",
		"maxTonsMult":10,
		"priceRange":[6000,14000],
		"purchaseDM":{"In":2, "Ht":3, "Ri":1},
		"saleDM":{"Ni":2, "Lt":1, "Po":1},
		"maxRisk":0,
		"dangerousGoodsDM":-6},

"12":{"type":"Basic Machine Parts",
		"available":["All"],
		"maxTonsDie":"1d6",
		"maxTonsMult":10,
		"priceRange":[8000, 12000],
		"purchaseDM":{"Na":2, "In":5},
		"saleDM":{"Ni":3, "Ag":2},
		"maxRisk":0,
		"dangerousGoodsDM":-6},

"13":{"type":"Basic Manufactured Goods",
		"available":["All"],
		"maxTonsDie":"1d6",
		"maxTonsMult":10,
		"priceRange":[8000, 12000],
		"purchaseDM":{"Na":2, "In":5},
		"saleDM":{"Ni":3, "Hi":2},
		"maxRisk":0,
		"dangerousGoodsDM":-6},

"14":{"type":"Basic Raw Materials",
		"available":["All"],
		"maxTonsDie":"1d6",
		"maxTonsMult":10,
		"priceRange":[1000, 9000],
		"purchaseDM":{"Ag":3, "Ga":2},
		"saleDM":{"In":2, "Po":2},
		"maxRisk":0,
		"dangerousGoodsDM":-6},

"15":{"type":"Basic Consumables",
		"available":["All"],
		"maxTonsDie":"1d6",
		"maxTonsMult":10,
		"priceRange":[500, 5000],
		"purchaseDM":{"Ag":3, "Wa":2, "Ga":1, "As":4},
		"saleDM":{"As":1, "Fl":1, "Ic":1, "Hi":1},
		"maxRisk":0,
		"dangerousGoodsDM":-6},

"16":{"type":"Basic Ore",
		"available":["All"],
		"maxTonsDie":"1d6",
		"maxTonsMult":10,
		"priceRange":[250, 2000],
		"purchaseDM":{"As":4},
		"saleDM":{"In":3, "Ni":1},
		"maxRisk":0,
		"dangerousGoodsDM":-6},

"21":{"type":"Advanced Electronics",
		"available":["In", "Ht"],
		"maxTonsDie":"1d6",
		"maxTonsMult":5,
		"priceRange":[25000, 150000],
		"purchaseDM":{"In":2, "Ht":3},
		"saleDM":{"Ni":1, "Ri":2, "As":3},
		"maxRisk":2,
		"dangerousGoodsDM":-2},

"22":{"type":"Advanced Machine Parts",
		"available":["In", "Ht"],
		"maxTonsDie":"1d6",
		"maxTonsMult":5,
		"priceRange":[25000, 100000],
		"purchaseDM":{"In":2, "Ht":1},
		"saleDM":{"As":2, "Ni":1},
		"maxRisk":2,
		"dangerousGoodsDM":-2},
		
"23":{"type":"Advanced Manufactured Goods",
		"available":["In", "Ht"],
		"maxTonsDie":"1d6",
		"maxTonsMult":5,
		"priceRange":[25000, 100000],
		"purchaseDM":{"In":1},
		"saleDM":{"Hi":1, "Ri":2},
		"maxRisk":2,
		"dangerousGoodsDM":-2},

"24":{"type":"Advanced Weapons",
		"available":["In", "Ht"],
		"maxTonsDie":"1d6",
		"maxTonsMult":5,
		"priceRange":[50000, 250000],
		"purchaseDM":{"Ht":2},
		"saleDM":{"Po":1, "Az":2, "Rz":4},
		"maxRisk":3,
		"dangerousGoodsDM":0},

"25":{"type":"Advanced Vehicles",
		"available":["In", "Ht"],
		"maxTonsDie":"1d6",
		"maxTonsMult":5,
		"priceRange":[100000, 250000],
		"purchaseDM":{"Ht":2},
		"saleDM":{"As":2, "Ri":2},
		"maxRisk":3,
		"dangerousGoodsDM":0},

"26":{"type":"Biochemicals",
		"available":["In", "Ht"],
		"maxTonsDie":"1d6",
		"maxTonsMult":5,
		"priceRange":[10000, 80000],
		"purchaseDM":{"Ag":1, "Wa":2},
		"saleDM":{"In":2},
		"maxRisk":2,
		"dangerousGoodsDM":2},

"31":{"type":"Crystals and Gems",
		"available":["As", "De", "Ic"],
		"maxTonsDie":"1d6",
		"maxTonsMult":5,
		"priceRange":[5000, 45000],
		"purchaseDM":{"As":2, "De":1, "Ic":1},
		"saleDM":{"In":3, "Ri":2},
		"maxRisk":2,
		"dangerousGoodsDM":-1},

"32":{"type":"Cybernetics",
		"available":["Ht"],
		"maxTonsDie":"1d6",
		"maxTonsMult":1,
		"priceRange":[100000, 500000],
		"purchaseDM":{},
		"saleDM":{"As":1, "Ic":1, "Ri":2},
		"maxRisk":3,
		"dangerousGoodsDM":1},

"33":{"type":"Live Animals",
		"available":["Ag", "Ga"],
		"maxTonsDie":"1d6",
		"maxTonsMult":10,
		"priceRange":[2500, 15000],
		"purchaseDM":{"Ag":2},
		"saleDM":{"Lo":3},
		"maxRisk":2,
		"dangerousGoodsDM":2},

"34":{"type":"Luxury Consumables",
		"available":["Ag", "Ga", "Wa"],
		"maxTonsDie":"1d6",
		"maxTonsMult":10,
		"priceRange":[5000, 50000],
		"purchaseDM":{"Ag":2, "Wa":1},
		"saleDM":{"Ri":2, "Hi":2},
		"maxRisk":3,
		"dangerousGoodsDM":2},

"35":{"type":"Luxury Goods",
		"available":["Hi"],
		"maxTonsDie":"1d6",
		"maxTonsMult":1,
		"priceRange":[50000, 500000],
		"purchaseDM":{},
		"saleDM":{"Ri":4},
		"maxRisk":3,
		"dangerousGoodsDM":2},

"36":{"type":"Medical Supplies",
		"available":["Ht","Hi"],
		"maxTonsDie":"1d6",
		"maxTonsMult":5,
		"priceRange":[10000, 100000],
		"purchaseDM":{"Ht":2},
		"saleDM":{"In":2, "Po":1, "Ri":1},
		"maxRisk":2,
		"dangerousGoodsDM":2},

"41":{"type":"Petrochemicals",
		"available":["De", "Fl", "Ic", "Wa"],
		"maxTonsDie":"1d6",
		"maxTonsMult":10,
		"priceRange":[2500, 30000],
		"purchaseDM":{"De":2},
		"saleDM":{"In":2, "Ag":1, "Lt":2},
		"maxRisk":2,
		"dangerousGoodsDM":2},

"42":{"type":"Pharmaceuticals",
		"available":["As", "De", "Hi", "Wa"],
		"maxTonsDie":"1d6",
		"maxTonsMult":1,
		"priceRange":[25000, 500000],
		"purchaseDM":{"As":2, "Hi":1},
		"saleDM":{"Ri":2, "Lt":1},
		"maxRisk":2,
		"dangerousGoodsDM":3},

"43":{"type":"Polymers",
		"available":["In"],
		"maxTonsDie":"1d6",
		"maxTonsMult":10,
		"priceRange":[1000, 10000],
		"purchaseDM":{},
		"saleDM":{"Ri":2, "Ni":1},
		"maxRisk":1,
		"dangerousGoodsDM":0},

"44":{"type":"Precious Metals",
		"available":["As", "De", "Ic", "Fl"],
		"maxTonsDie":"1d6",
		"maxTonsMult":1,
		"priceRange":[10000, 100000],
		"purchaseDM":{"As":3, "De":1, "Ic":2},
		"saleDM":{"Ri":2, "In":2, "Ht":1},
		"maxRisk":3,
		"dangerousGoodsDM":4},

"45":{"type":"Radioactives",
		"available":["As", "De", "Lo"],
		"maxTonsDie":"1d6",
		"maxTonsMult":1,
		"priceRange":[500000, 1500000],
		"purchaseDM":{"As":2, "Lo":2},
		"saleDM":{"In":3, "Ht":1, "Ni":-2, "Ag":-3},
		"maxRisk":4,
		"dangerousGoodsDM":3},

"46":{"type":"Robots",
		"available":["In"],
		"maxTonsDie":"1d6",
		"maxTonsMult":5,
		"priceRange":[150000, 650000],
		"purchaseDM":{},
		"saleDM":{"Ag":2, "Ht":1},
		"maxRisk":2,
		"dangerousGoodsDM":1},

"51":{"type":"Spices",
		"available":["Ga", "De", "Wa"],
		"maxTonsDie":"1d6",
		"maxTonsMult":5,
		"priceRange":[1000, 12000],
		"purchaseDM":{"De":2},
		"saleDM":{"Hi":2, "Ri":3, "Po":3},
		"maxRisk":2,
		"dangerousGoodsDM":-1},

"52":{"type":"Textiles",
		"available":["Ag", "Ni"],
		"maxTonsDie":"1d6",
		"maxTonsMult":10,
		"priceRange":[1000, 5000],
		"purchaseDM":{"Ag":7},
		"saleDM":{"Hi":3, "Na":2},
		"maxRisk":1,
		"dangerousGoodsDM":-2},

"53":{"type":"Uncommon Ore",
		"available":["As", "Ic"],
		"maxTonsDie":"1d6",
		"maxTonsMult":10,
		"priceRange":[1000, 10000],
		"purchaseDM":{"As":4},
		"saleDM":{"In":3, "Ni":1},
		"maxRisk":2,
		"dangerousGoodsDM":-2},

"54":{"type":"Uncommon Raw Materials",
		"available":["Ag", "De", "Wa"],
		"maxTonsDie":"1d6",
		"maxTonsMult":10,
		"priceRange":[5000, 50000],
		"purchaseDM":{"Ag":2, "Wa":1},
		"saleDM":{"In":2, "Ht":1},
		"maxRisk":2,
		"dangerousGoodsDM":-2},

"55":{"type":"Wood",
		"available":["Ag", "Ga"],
		"maxTonsDie":"1d6",
		"maxTonsMult":10,
		"priceRange":[100, 4000],
		"purchaseDM":{"Ag":6},
		"saleDM":{"Ri":2, "In":1},
		"maxRisk":1,
		"dangerousGoodsDM":-4},

"56":{"type":"Vehicles",
		"available":["In", "Ht"],
		"maxTonsDie":"1d6",
		"maxTonsMult":10,
		"priceRange":[5000, 30000],
		"purchaseDM":{"In":2, "Ht":1},
		"saleDM":{"Ni":2, "Hi":1},
		"maxRisk":2,
		"dangerousGoodsDM":-2},

"61":{"type":"Illegal Biochemicals",
		"available":["Ag", "Wa"],
		"maxTonsDie":"1d6",
		"maxTonsMult":5,
		"priceRange":[10000, 200000],
		"purchaseDM":{"Wa":2},
		"saleDM":{"In":6},
		"maxRisk":4,
		"dangerousGoodsDM":4},

"62":{"type":"Illegal Cybernetics",
		"available":["Ht"],
		"maxTonsDie":"1d6",
		"maxTonsMult":1,
		"priceRange":[100000, 650000],
		"purchaseDM":{},
		"saleDM":{"As":4, "Ic":4, "Ri":8, "Az":6, "Rz":6},
		"maxRisk":5,
		"dangerousGoodsDM":5},

"63":{"type":"Illegal Drugs",
		"available":["As", "De", "Hi", "Wa"],
		"maxTonsDie":"1d6",
		"maxTonsMult":1,
		"priceRange":[25000, 300000],
		"purchaseDM":{},
		"saleDM":{"Ri":6, "Hi":6},
		"maxRisk":4,
		"dangerousGoodsDM":6},

"64":{"type":"Illegal Luxuries",
		"available":["Ag", "Ga", "Wa"],
		"maxTonsDie":"1d6",
		"maxTonsMult":1,
		"priceRange":[10000, 200000],
		"purchaseDM":{"Ag":2, "Wa":1},
		"saleDM":{"Ri":6, "Hi":4},
		"maxRisk":4,
		"dangerousGoodsDM":4},

"65":{"type":"Illegal Weapons",
		"available":["In", "Ht"],
		"maxTonsDie":"1d6",
		"maxTonsMult":5,
		"priceRange":[50000, 450000],
		"purchaseDM":{"Ht":2},
		"saleDM":{"Po":6, "Az":8, "Rz":10},
		"maxRisk":5,
		"dangerousGoodsDM":6}

		
}

{
 11:{
		2:{
			"definedTradeGood":"Calculators/Adding Machines",
			"tons":function(){return rawroll(1,6).total * 12},
			"basePrice":6000
			},
		5:{
			"definedTradeGood":"Video Game and Entertainment Systems",
			"tons":function(){return rawroll(1,6).total * 10},
			"basePrice":8000
			},
		8:{
			"definedTradeGood":"Personal and Commercial Computers",
			"tons":function(){return rawroll(1,6).total * 10},
			"basePrice":10000
			},
		11:{
			"definedTradeGood":"Banking Machines and Security Systems",
			"tons":function(){return rawroll(1,6).total * 4},
			"basePrice":12000
			},
		12:{
			"definedTradeGood":"Microprocessor Assemblies",
			"tons":function(){return rawroll(1,6).total * 2},
			"basePrice":14000
			}
		},
12:{
		2:{
			"definedTradeGood":"",
			"tons":function(){return rawroll(,).total * },
			"basePrice":
			},
		5:{
			"definedTradeGood":"",
			"tons":function(){return rawroll(,).total * },
			"basePrice":
			},
		8:{
			"definedTradeGood":"",
			"tons":function(){return rawroll(,).total * },
			"basePrice":
			},
		11:{
			"definedTradeGood":"",
			"tons":function(){return rawroll(,).total * },
			"basePrice":
			},
		12:{
			"definedTradeGood":"",
			"tons":function(){return rawroll(,).total * },
			"basePrice":
			}
		},
		
		
}

